/** Synthetic-only source bundle for the street-lighting PM walkthrough and AI intake. */
export const streetlightSourcePack = [
  {
    name: '01-project-brief.md',
    mediaType: 'text/markdown',
    text: [
      'SCENARIU SINTETIC: modernizarea iluminatului public din Bălți.',
      'Toate numele, rolurile, datele și afirmațiile din acest pachet sunt demonstrative.',
      'Manager de proiect: Elena Rusu; coordonează planul și aprobările.',
      'Inginer proiectare: Victor Munteanu; pregătește documentația tehnică.',
      'Revizie tehnică și legătura cu beneficiarul: Irina Ceban.',
      'Aprovizionare și legătura cu furnizorul: Mihai Lungu.',
      'Livrabil intermediar: planul tehnic pentru modernizarea rețelei de iluminat stradal.',
      'Planul de lucru demonstrativ indică 30 septembrie 2026 ca dată țintă pentru planul intermediar.',
      'După planul intermediar urmează revizia tehnică.',
      'După revizia tehnică urmează aprobarea beneficiarului.',
      'În acest scenariu nu este înregistrată o dată contractuală pentru livrarea echipamentelor.',
    ].join('\n'),
  },
  {
    name: '02-work-plan.md',
    mediaType: 'text/markdown',
    text: [
      'Plan de lucru demonstrativ · revizia 1.',
      'T-01 · Pregătește planul tehnic intermediar · responsabil: Victor Munteanu · în lucru · termen țintă: 2026-09-30.',
      'T-02 · Revizie tehnică a planului intermediar · responsabil: Irina Ceban · neînceput · după T-01.',
      'T-03 · Obține aprobarea beneficiarului · responsabil: Irina Ceban · neînceput · după T-02.',
      'T-04 · Confirmă data livrării echipamentelor cu furnizorul · responsabil: Mihai Lungu · în așteptarea confirmării · dată necunoscută.',
      'T-05 · Pregătește dosarul de achiziție · responsabil: Mihai Lungu · neînceput · după confirmarea specificațiilor tehnice.',
      'T-06 · Revizuiește data furnizorului la următorul check-in · responsabil: Elena Rusu · în așteptare · după T-04.',
      'D-01 · Plan tehnic intermediar · termen de referință: 2026-09-30 · depinde de T-01.',
      'D-02 · Pachet tehnic aprobat · data de referință nu este înregistrată · depinde de T-03.',
    ].join('\n'),
  },
  {
    name: '03-progress-note.md',
    mediaType: 'text/markdown',
    text: [
      'Notă de progres demonstrativă · 26 septembrie 2026.',
      'Relatarea managerului: furnizorul nu a confirmat încă data livrării echipamentelor.',
      'Răspunsul direct al furnizorului nu este inclus în sursele demonstrative.',
      'Mihai Lungu urmărește confirmarea și va raporta răspunsul la următorul check-in.',
      'Nu s-a înregistrat o dată nouă pentru planul intermediar; ținta documentată rămâne 30 septembrie 2026.',
      'Managerul nu a confirmat dacă versiunea intermediară poate fi transmisă înaintea pachetului final.',
    ].join('\n'),
  },
  {
    name: '04-meeting-handoffs.md',
    mediaType: 'text/markdown',
    text: [
      'Notă de coordonare demonstrativă · 25 septembrie 2026.',
      'Elena Rusu i-a cerut lui Mihai Lungu să obțină de la furnizor o dată de livrare confirmată.',
      'Mihai Lungu va raporta starea confirmării către Elena Rusu la următorul check-in.',
      'Elena Rusu va revizui data confirmată după raportarea lui Mihai Lungu.',
      'Victor Munteanu predă planul intermediar către Irina Ceban pentru revizia tehnică.',
      'După revizia tehnică, Irina Ceban coordonează trimiterea pachetului pentru aprobarea beneficiarului.',
    ].join('\n'),
  },
  {
    name: '05-deliverables.csv',
    mediaType: 'text/csv',
    text: [
      'id,title,owner,status,target_date,depends_on',
      'T-01,Pregătește planul tehnic intermediar,Victor Munteanu,in_progress,2026-09-30,',
      'T-02,Revizie tehnică a planului intermediar,Irina Ceban,not_started,,T-01',
      'T-03,Obține aprobarea beneficiarului,Irina Ceban,not_started,,T-02',
      'T-04,Confirmă data livrării echipamentelor cu furnizorul,Mihai Lungu,waiting_for_confirmation,,',
      'T-05,Pregătește dosarul de achiziție,Mihai Lungu,not_started,,T-02',
      'T-06,Revizuiește data furnizorului la următorul check-in,Elena Rusu,waiting_for_confirmation,,T-04',
      'D-01,Plan tehnic intermediar,,planned,2026-09-30,T-01',
      'D-02,Pachet tehnic aprobat,,planned,,T-03',
    ].join('\n'),
  },
  {
    name: '06-team-and-delivery-plan.md',
    mediaType: 'text/markdown',
    text: [
      'SCENARIU SINTETIC · Plan detaliat și capacitate declarată · 27 septembrie 2026. Toate datele sunt fictive.',
      'Elena Rusu: coordonare, urmărire angajamente și raportare; disponibilitate declarată 3 zile/săptămână până la 2026-10-16.',
      'Victor Munteanu: proiectare electrică, scheme și specificații; disponibilitate declarată 4 zile/săptămână până la 2026-10-16.',
      'Irina Ceban: verificare tehnică, comunicare cu beneficiarul; disponibilitate declarată 2 zile/săptămână până la 2026-10-16.',
      'Mihai Lungu: achiziții, comparație oferte și relația cu furnizorul; disponibilitate declarată 3 zile/săptămână până la 2026-10-16.',
      'Sofia Dinu: verificatoare cantități; competențe documentate în scenariu: devize și verificare liste materiale; disponibilitate declarată 2 zile/săptămână până la 2026-10-16.',
      'Andrei Rotaru: coordonator instalare; competențe documentate în scenariu: organizare șantier și securitate electrică; disponibilitatea pentru execuție nu este confirmată.',
      'Dana Moraru: sponsor, aprobă resursele și schimbările de scop; competențe documentate în scenariu: guvernanță și bugete; intervalul pentru decizii nu este confirmat.',
      'T-07 · Verifică inventarul punctelor de iluminat · responsabil: Sofia Dinu · finalizat la 2026-09-25 · start 2026-09-23 · durată planificată 2 zile lucrătoare · efort 12 ore.',
      'T-08 · Verifică lista de materiale · responsabil: Sofia Dinu · în lucru · după T-01 · termen 2026-10-02 · start 2026-10-01 · durată planificată 2 zile lucrătoare · efort 10 ore.',
      'T-09 · Compară ofertele tehnice · responsabil: Mihai Lungu · neînceput · după T-05 și T-08 · termen 2026-10-06 · start 2026-10-05 · durată planificată 2 zile lucrătoare · efort 12 ore.',
      'T-10 · Decide suplimentarea capacității · responsabil: Dana Moraru · în așteptare · după T-06 · termen 2026-10-02 · start 2026-10-02 · durată planificată 1 zi lucrătoare · efort 2 ore.',
      'T-11 · Pregătește planul de instalare · responsabil: Andrei Rotaru · neînceput · după T-03 și T-09 · termen 2026-10-09 · start 2026-10-07 · durată planificată 3 zile lucrătoare · efort 16 ore.',
      'T-12 · Revizuiește planul de siguranță · responsabil: Irina Ceban · neînceput · după T-11 · termen 2026-10-12 · start 2026-10-12 · durată planificată 1 zi lucrătoare · efort 4 ore.',
      'T-13 · Pregătește raportul pentru client · responsabil: Elena Rusu · în lucru · după T-02 · termen 2026-10-05 · start 2026-10-05 · durată planificată 1 zi lucrătoare · efort 3 ore.',
      'T-14 · Confirmă fereastra de instalare · responsabil: Andrei Rotaru · neînceput · după T-04 și T-12 · termen necunoscut · durată și efort neconfirmate.',
      'Sofia predă lista verificată lui Mihai; Mihai transmite ofertele comparate lui Andrei; Andrei predă planul de siguranță Irinei; Elena escaladează suplimentarea capacității către Dana.',
      'Estimările de efort nu reprezintă durată calendaristică. Datele planificate nu sunt promisiuni confirmate de furnizor. Jurnalul de progres sintetic este separat în 08-progress-history.md.',
    ].join('\n'),
  },
  {
    name: '07-project-register.md',
    mediaType: 'text/markdown',
    text: [
      'Registru demonstrativ complet · pregătit manual pentru prezentare · 27 septembrie 2026.',
      'Radu Ionescu · tehnician măsurători · competențe declarate: măsurători electrice și verificări de teren · disponibilitate declarată 3 zile/săptămână până la 2026-10-16.',
      'Ioana Popa · coordonatoare documente · competențe declarate: control versiuni și arhivare · disponibilitate declarată 2 zile/săptămână până la 2026-10-16.',
      'Oleg Balan · șef echipă teren · competențe declarate: instalare corpuri LED și verificări după montaj · disponibilitate declarată 3 zile/săptămână până la 2026-10-16.',
      'T-15 · Marchează punctele de control pe teren · responsabil: Sofia Dinu · finalizat · start 2026-09-21 · durată planificată 1 zi lucrătoare · efort 5 ore · termen 2026-09-22.',
      'T-16 · Măsoară circuitele de probă · responsabil: Radu Ionescu · finalizat · start 2026-09-22 · durată planificată 1 zi lucrătoare · efort 7 ore · termen 2026-09-23 · după T-15.',
      'T-17 · Validează coordonatele punctelor de lumină · responsabil: Sofia Dinu · finalizat · start 2026-09-23 · durată planificată 1 zi lucrătoare · efort 6 ore · termen 2026-09-24 · după T-15.',
      'T-18 · Pregătește modelul de comparație a ofertelor · responsabil: Mihai Lungu · finalizat · start 2026-09-25 · durată planificată 1 zi lucrătoare · efort 4 ore · termen 2026-09-26.',
      'T-19 · Verifică accesul pentru montaj · responsabil: Andrei Rotaru · neînceput · start planificat 2026-10-16 · durată planificată 2 zile lucrătoare · efort 8 ore · termen 2026-10-19 · după T-11.',
      'T-20 · Verifică instalația după montaj · responsabil: Oleg Balan · neînceput · start planificat 2026-10-20 · durată planificată 2 zile lucrătoare · efort 8 ore · termen 2026-10-21 · după T-12 și T-19.',
      'T-01 · Pregătește planul tehnic intermediar · start planificat 2026-09-28 · durată planificată 3 zile lucrătoare · efort 16 ore.',
      'T-02 · Revizie tehnică a planului · start planificat 2026-10-01 · durată planificată 2 zile lucrătoare · efort 8 ore.',
      'T-03 · Obține aprobarea beneficiarului · start planificat 2026-10-06 · durată planificată 1 zi lucrătoare · efort 3 ore.',
      'T-04 · Confirmă data livrării echipamentelor cu furnizorul · durata și termenul rămân neconfirmate.',
      'T-05 · Pregătește dosarul de achiziție · start planificat 2026-10-05 · durată planificată 2 zile lucrătoare · efort 8 ore.',
      'T-06 · Revizuiește data furnizorului la următorul check-in · durata și termenul rămân neconfirmate.',
      'Predare demonstrativă: Radu transmite măsurătorile către Sofia; Sofia predă lista către Mihai; Mihai transmite comparația către Andrei; Ioana arhivează versiunea acceptată de Victor.',
      'D-03 · Fișă de verificare după montaj · planificată pentru 2026-10-22 · depinde de T-20.',
      'R-02 · Durata aprobării beneficiarului nu este consemnată; orice întârziere din preset este ipoteză editabilă, nu termen confirmat.',
      'R-03 · Fereastra de acces la teren pentru montaj nu este confirmată; cere confirmarea înainte de programarea echipei.',
    ].join('\n'),
  },
  {
    name: '08-progress-history.md',
    mediaType: 'text/markdown',
    text: [
      'Jurnal sintetic de finalizări, consemnat pentru acest scenariu demonstrativ; scopul registrului este cel curent.',
      'La 2026-09-22, T-15 a fost marcat finalizat după verificarea punctelor de control pe teren.',
      'La 2026-09-23, T-16 a fost marcat finalizat după măsurarea circuitelor de probă.',
      'La 2026-09-24, T-17 a fost marcat finalizat după validarea coordonatelor punctelor de lumină.',
      'La 2026-09-25, T-07 a fost marcat finalizat după verificarea inventarului punctelor de iluminat.',
      'La 2026-09-26, T-18 a fost marcat finalizat după pregătirea modelului de comparație; ofertele furnizorilor nu sunt incluse.',
    ].join('\n'),
  },
  {
    name: '09-collaboration-notes.md',
    mediaType: 'text/markdown',
    text: [
      'Note de colaborare declarate pentru scenariul sintetic · nu sunt teste psihometrice sau scoruri de compatibilitate.',
      'Elena Rusu declară: competențe de coordonare și raportare; preferă un rezumat scris înainte de check-in și să primească raportul lui Mihai înaintea reviziei.',
      'Victor Munteanu declară: competențe de proiectare și documentare; preferă scheme versionate și întrebări de revizie grupate pentru Irina.',
      'Irina Ceban declară: competențe de revizie tehnică și comunicare; preferă ca Victor să atașeze lista punctelor verificate la fiecare predare.',
      'Mihai Lungu declară: competențe de achiziții și urmărire furnizori; preferă să transmită Elenei statusul confirmării înainte de check-in.',
      'Sofia Dinu declară: competențe de devize și verificare materiale; preferă să predea lui Mihai o listă cu abaterile marcate.',
      'Andrei Rotaru declară: competențe de organizare a șantierului și securitate electrică; preferă să trimită Irinei planul de siguranță pentru revizie.',
      'Dana Moraru declară: competențe de guvernanță și bugete; preferă să primească de la Elena două opțiuni și impactul lor înaintea unei decizii.',
      'Radu Ionescu declară: competențe de măsurători electrice și verificări de teren; preferă să transmită Sofiei fișele de măsurători în aceeași zi.',
      'Ioana Popa declară: competențe de control versiuni și arhivare; preferă să primească de la Victor versiunea tehnică acceptată înainte de arhivare.',
      'Oleg Balan declară: competențe de instalare LED și verificări după montaj; preferă să alinieze accesul la teren cu Andrei înainte de instalare.',
    ].join('\n'),
  },
  {
    name: '10-review-options.md',
    mediaType: 'text/markdown',
    text: [
      'Opțiuni demonstrative propuse pentru revizia PM; nu au fost aprobate și nu modifică registrul curent.',
      'Propunere neaprobată: dacă fereastra de acces se confirmă, T-14 poate fi programată pentru 2026-10-15 cu o zi de lucru și două ore de efort; cere confirmarea PM-ului.',
      'Propunere neaprobată: după verificarea T-20, Oleg Balan poate primi sarcina „Verifică iluminarea după montaj” pe 2026-10-22; durata estimată este o zi și efortul patru ore.',
    ].join('\n'),
  },
] as const;
