/** Synthetic-only source bundle for the street-lighting PM walkthrough and AI intake. */
export const streetlightSourcePack = [
  {
    name: '01-project-brief.md',
    mediaType: 'text/markdown',
    text: [
      'SCENARIU SINTETIC: modernizarea iluminatului public din Bălți.',
      'Toate numele, rolurile, datele și afirmațiile din acest pachet sunt demonstrative.',
      'Manager de proiect: Elena Rusu; coordonează planul și aprobările.',
      'Inginer proiectare: Victor Munteanu; pregătește documentația tehnică.',
      'Revizie tehnică și legătura cu beneficiarul: Irina Ceban.',
      'Aprovizionare și legătura cu furnizorul: Mihai Lungu.',
      'Livrabil intermediar: planul tehnic pentru modernizarea rețelei de iluminat stradal.',
      'Planul de lucru demonstrativ indică 30 septembrie 2026 ca dată țintă pentru planul intermediar.',
      'După planul intermediar urmează revizia tehnică.',
      'După revizia tehnică urmează aprobarea beneficiarului.',
      'În acest scenariu nu este înregistrată o dată contractuală pentru livrarea echipamentelor.',
    ].join('\n'),
  },
  {
    name: '02-work-plan.md',
    mediaType: 'text/markdown',
    text: [
      'Plan de lucru demonstrativ · revizia 1.',
      'T-01 · Pregătește planul tehnic intermediar · responsabil: Victor Munteanu · în lucru · termen țintă: 2026-09-30.',
      'T-02 · Revizie tehnică a planului intermediar · responsabil: Irina Ceban · neînceput · după T-01.',
      'T-03 · Obține aprobarea beneficiarului · responsabil: Irina Ceban · neînceput · după T-02.',
      'T-04 · Confirmă data livrării echipamentelor cu furnizorul · responsabil: Mihai Lungu · în așteptarea confirmării · dată necunoscută.',
      'T-05 · Pregătește dosarul de achiziție · responsabil: Mihai Lungu · neînceput · după confirmarea specificațiilor tehnice.',
      'T-06 · Revizuiește data furnizorului la următorul check-in · responsabil: Elena Rusu · în așteptare · după T-04.',
      'D-01 · Plan tehnic intermediar · termen de referință: 2026-09-30 · depinde de T-01.',
      'D-02 · Pachet tehnic aprobat · data de referință nu este înregistrată · depinde de T-03.',
    ].join('\n'),
  },
  {
    name: '03-progress-note.md',
    mediaType: 'text/markdown',
    text: [
      'Notă de progres demonstrativă · 26 septembrie 2026.',
      'Relatarea managerului: furnizorul nu a confirmat încă data livrării echipamentelor.',
      'Răspunsul direct al furnizorului nu este inclus în sursele demonstrative.',
      'Mihai Lungu urmărește confirmarea și va raporta răspunsul la următorul check-in.',
      'Nu s-a înregistrat o dată nouă pentru planul intermediar; ținta documentată rămâne 30 septembrie 2026.',
      'Managerul nu a confirmat dacă versiunea intermediară poate fi transmisă înaintea pachetului final.',
    ].join('\n'),
  },
  {
    name: '04-meeting-handoffs.md',
    mediaType: 'text/markdown',
    text: [
      'Notă de coordonare demonstrativă · 25 septembrie 2026.',
      'Elena Rusu i-a cerut lui Mihai Lungu să obțină de la furnizor o dată de livrare confirmată.',
      'Mihai Lungu va raporta starea confirmării către Elena Rusu la următorul check-in.',
      'Elena Rusu va revizui data confirmată după raportarea lui Mihai Lungu.',
      'Victor Munteanu predă planul intermediar către Irina Ceban pentru revizia tehnică.',
      'După revizia tehnică, Irina Ceban coordonează trimiterea pachetului pentru aprobarea beneficiarului.',
    ].join('\n'),
  },
  {
    name: '05-deliverables.csv',
    mediaType: 'text/csv',
    text: [
      'id,title,owner,status,target_date,depends_on',
      'T-01,Pregătește planul tehnic intermediar,Victor Munteanu,in_progress,2026-09-30,',
      'T-02,Revizie tehnică a planului intermediar,Irina Ceban,not_started,,T-01',
      'T-03,Obține aprobarea beneficiarului,Irina Ceban,not_started,,T-02',
      'T-04,Confirmă data livrării echipamentelor cu furnizorul,Mihai Lungu,waiting_for_confirmation,,',
      'T-05,Pregătește dosarul de achiziție,Mihai Lungu,not_started,,T-02',
      'T-06,Revizuiește data furnizorului la următorul check-in,Elena Rusu,waiting_for_confirmation,,T-04',
      'D-01,Plan tehnic intermediar,,planned,2026-09-30,T-01',
      'D-02,Pachet tehnic aprobat,,planned,,T-03',
    ].join('\n'),
  },
  {
    name: '06-team-and-delivery-plan.md',
    mediaType: 'text/markdown',
    text: [
      'SCENARIU SINTETIC · Plan detaliat și capacitate declarată · 27 septembrie 2026. Toate datele sunt fictive.',
      'Elena Rusu: coordonare, urmărire angajamente și raportare; disponibilitate declarată 3 zile/săptămână până la 2026-10-16.',
      'Victor Munteanu: proiectare electrică, scheme și specificații; disponibilitate declarată 4 zile/săptămână până la 2026-10-16.',
      'Irina Ceban: verificare tehnică, comunicare cu beneficiarul; disponibilitate declarată 2 zile/săptămână până la 2026-10-16.',
      'Mihai Lungu: achiziții, comparație oferte și relația cu furnizorul; disponibilitate declarată 3 zile/săptămână până la 2026-10-16.',
      'Sofia Dinu: verificatoare cantități; competențe documentate în scenariu: devize și verificare liste materiale; disponibilitate declarată 2 zile/săptămână până la 2026-10-16.',
      'Andrei Rotaru: coordonator instalare; competențe documentate în scenariu: organizare șantier și securitate electrică; disponibilitatea pentru execuție nu este confirmată.',
      'Dana Moraru: sponsor, aprobă resursele și schimbările de scop; competențe documentate în scenariu: guvernanță și bugete; intervalul pentru decizii nu este confirmat.',
      'T-07 · Verifică inventarul punctelor de iluminat · responsabil: Sofia Dinu · finalizat la 2026-09-25 · start 2026-09-23 · durată planificată 2 zile lucrătoare · efort 12 ore.',
      'T-08 · Verifică lista de materiale · responsabil: Sofia Dinu · în lucru · după T-01 · termen 2026-10-02 · start 2026-10-01 · durată planificată 2 zile lucrătoare · efort 10 ore.',
      'T-09 · Compară ofertele tehnice · responsabil: Mihai Lungu · neînceput · după T-05 și T-08 · termen 2026-10-06 · start 2026-10-05 · durată planificată 2 zile lucrătoare · efort 12 ore.',
      'T-10 · Decide suplimentarea capacității · responsabil: Dana Moraru · în așteptare · după T-06 · termen 2026-10-02 · start 2026-10-02 · durată planificată 1 zi lucrătoare · efort 2 ore.',
      'T-11 · Pregătește planul de instalare · responsabil: Andrei Rotaru · neînceput · după T-03 și T-09 · termen 2026-10-09 · start 2026-10-07 · durată planificată 3 zile lucrătoare · efort 16 ore.',
      'T-12 · Revizuiește planul de siguranță · responsabil: Irina Ceban · neînceput · după T-11 · termen 2026-10-12 · start 2026-10-12 · durată planificată 1 zi lucrătoare · efort 4 ore.',
      'T-13 · Pregătește raportul pentru client · responsabil: Elena Rusu · în lucru · după T-02 · termen 2026-10-05 · start 2026-10-05 · durată planificată 1 zi lucrătoare · efort 3 ore.',
      'T-14 · Confirmă fereastra de instalare · responsabil: Andrei Rotaru · neînceput · după T-04 și T-12 · termen necunoscut · durată și efort neconfirmate.',
      'Sofia predă lista verificată lui Mihai; Mihai transmite ofertele comparate lui Andrei; Andrei predă planul de siguranță Irinei; Elena escaladează suplimentarea capacității către Dana.',
      'Estimările de efort nu reprezintă durată calendaristică. Datele planificate nu sunt promisiuni confirmate de furnizor. Nu există istoric zilnic suficient pentru burndown.',
    ].join('\n'),
  },
] as const;
